#! /bin/sh

AOC_YEAR="$1"
AOC_DAY="$2"

if [ -z $AOC_YEAR ] || [ -z $AOC_DAY ]; then
    echo "Please pass a year and day as args"
    exit 1
fi

if [ ! -e ./.session-id ]; then
	echo 'Advent of Code session cookie must be saved in ".session-id" text file.'
	exit 2
fi 

AOC_SESSION_ID=$(cat .session-id)

AOC_DIR="$AOC_YEAR/$AOC_DAY"

mkdir -p $AOC_DIR

curl -b session=$AOC_SESSION_ID https://adventofcode.com/${AOC_YEAR}/day/${AOC_DAY}/input > $AOC_DIR/input

unset AOC_YEAR
unset AOC_DAY
unset AOC_SESSION_ID
unset AOC_DIR
