#! /bin/bash

YEAR="2015"
DAY="$1"

mkdir -p "$1"

../get-input $YEAR $DAY

mv input "$1/input"

ML_FILE="$1/$1.ml"

touch $ML_FILE

printf "\n" >> $ML_FILE
printf "let ic = open_in \"$1/input\"\n" >> $ML_FILE
printf "\n" >> $ML_FILE
printf "let rec rl acc ic = match input_line ic with | s -> rl (s::acc) ic | exception End_of_file -> acc\n" >> $ML_FILE
printf "\n" >> $ML_FILE
printf "\n" >> $ML_FILE
printf "\n" >> $ML_FILE
printf "let () = close_in ic\n" >> $ML_FILE
printf "\n" >> $ML_FILE

